# Generated by Django 4.1.3 on 2022-12-07 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('user_id', models.CharField(blank=True, max_length=300, null=True)),
                ('fname', models.CharField(blank=True, max_length=300, null=True)),
                ('lname', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=300, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.CharField(blank=True, max_length=3000, null=True)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Submitted', max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('engg_username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
